name: celo_composer
description: "CLI tool for creating Celo blockchain projects"
version: 1.0.0+1
platforms:
  dart: ">=3.0.0 <4.0.0"

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.2
  web3dart: ^2.7.3
  args: ^2.6.0
  process_run: ^1.2.2+1
  yaml: ^3.1.0

  cupertino_icons: ^1.0.8
  chalkdart: ^2.2.1
  prompts: ^2.0.0
  yaml_writer: ^2.0.1
  path: ^1.9.0
  emojis: ^0.9.9
  cli_spinner: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
